global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'starlink'
    scrape_interval: 1s
    scrape_timeout:  1s
    static_configs:
      - targets: ['starlink_exporter:9817']
  - job_name: 'speedtest'
    scrape_interval: 30m
    scrape_timeout: 40s
    static_configs:
      - targets: [ 'speedtest_exporter:9090' ]
